version: "3.8"

services:
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: cromwell-api
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./api:/app
  #     - /app/node_modules
  #   depends_on:
  #     - db

  client:
    build: ./client
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: cromwell-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:15-alpine
    container_name: cromwell-db-test
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_test
    ports:
      - "25432:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
